### ISSUE TITLE
投稿に表示されている情報が重複

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fishing-map#45]
![image](https://user-images.githubusercontent.com/38624583/74603654-2ec59180-50f9-11ea-9ae3-6c3539055afe.png)

「日時」と「x日前」は同じ様な情報です．
あと，「日時」にも関わらず時間が無いです．

**Comment by mistake-git** [comment]
投稿した日と実際に魚を釣った日が異なる可能性があるので､分けていますが､混同しやすい
と思ったので"釣った日"に変更しました
