### ISSUE TITLE
複雑でない処理はViewで行う

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fishing-map#60]
https://github.com/mistake-git/Fishing_Map/blob/71eda6e04aa1fb29ec27c74ad58e050183b002df/app/controllers/users_controller.rb#L25-L30
データを取り出しているだけなので，スコープを狭めるためにControllerではなくViewで取り出したほうがいいと思います．

**Comment by rorenge7** [comment]
https://github.com/mistake-git/Fishing_Map/blob/71eda6e04aa1fb29ec27c74ad58e050183b002df/app/controllers/ranking_controller.rb#L6
こことかもわざわざインスタンス変数に入れる必要はなくて，Viewで直接表示すればいいと思います．

数が多く指摘しきれないのでこれぐらいでとどめておきます．

**Comment by mistake-git** [comment]
befor_actionで定義しました
