### ISSUE TITLE
Comment, Like, Postをパーシャルにする

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fishing-map#61]
https://github.com/mistake-git/Fishing_Map/blob/71eda6e04aa1fb29ec27c74ad58e050183b002df/app/views/users/comments.html.erb#L1
重複部分があるので，パーシャルで表示した方がいいと思います．

**Comment by mistake-git** [comment]
パーシャル分けを実装

**Comment by mistake-git** [comment]
Javascriptによるタブで実装しました。
