### ISSUE TITLE
関連付けられたモデルのとり方を修正

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fishing-map#62]
https://github.com/mistake-git/Fishing_Map/blob/71eda6e04aa1fb29ec27c74ad58e050183b002df/app/controllers/posts_controller.rb#L53
`@likes_count = @post.likes.count`の方が分かりやすいと思います．

**Comment by mistake-git** [comment]
修正しました

**Comment by rorenge7** [comment]
こことかもありますね．
https://github.com/mistake-git/Fishing_Map/blob/b1847d23eed2bd25d3712463ac5af1e1f1a7c664/app/controllers/posts_controller.rb#L54-L55
